excluded:
  - Pods

disabled_rules:
  - identifier_name

opt_in_rules:
  - attributes
  - balanced_xctest_lifecycle
  - capture_variable
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_xctest_method
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_objc_type
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  #- multiline_function_chains
  - multiline_parameters
  #- no_extension_access_modifier
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  #- trailing_closure
  - unneeded_parentheses_in_closure_argument
  #- unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60

line_length:
  warning: 230
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 70
  error: 120

implicitly_unwrapped_optional: error

force_unwrapping: error
